#! /bin/bash

rm code/*.class

javac code/Class0.java
javac code/Class1.java
javac -cp code:libs/junit-4.8.2.jar:libs/hamcrest-core-1.3.jar code/TestSuite.java
javac -cp code:libs/junit-4.8.2.jar code/SingleJUnitTestRunner.java
#java  -cp code:libs/junit-4.12.jar:libs/hamcrest-core-1.3.jar org.junit.runner.JUnitCore TestSuite
java -cp code:libs/junit-4.8.2.jar SingleJUnitTestRunner org.junit.runner.JUnitCore TestSuite#evaluatesExpression0

#java -cp path/to/testclasses:path/to/junit-4.8.2.jar SingleJUnitTestRunner com.mycompany.product.MyTest#testB
