#! /bin/bash

rm *.class

javac Class0.java
javac Class1.java
javac -cp .:junit-4.12.jar:hamcrest-core-1.3.jar TestSuite.java
java  -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore TestSuite
